# roles/collectd/tasks/main.yml
---

- name: Install packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: collectd_packages
  tags: collectd

- name: Ensure service is started
  service:
    name: "{{ collectd_service }}"
    state: started
    enabled: true
  tags: collectd
